import { FilmChallenge } from '@/types/media'

export const challenges: FilmChallenge[] = [
  {
    id: 'nolan-marathon',
    title: 'Nolan Marathon',
    description: 'Every Christopher Nolan film in chronological order',
    category: 'director',
    icon: '◎',
    totalRuntime: 1390,
    itemCount: 12,
    items: [
      {
        title: 'Following',
        year: '1998',
        runtime: 69,
        tmdbId: 11660,
        mediaType: 'movie',
      },
      {
        title: 'Memento',
        year: '2000',
        runtime: 113,
        tmdbId: 77,
        mediaType: 'movie',
      },
      {
        title: 'Insomnia',
        year: '2002',
        runtime: 118,
        tmdbId: 6217,
        mediaType: 'movie',
      },
      {
        title: 'Batman Begins',
        year: '2005',
        runtime: 140,
        tmdbId: 272,
        mediaType: 'movie',
      },
      {
        title: 'The Prestige',
        year: '2006',
        runtime: 130,
        tmdbId: 1124,
        mediaType: 'movie',
      },
      {
        title: 'The Dark Knight',
        year: '2008',
        runtime: 152,
        tmdbId: 155,
        mediaType: 'movie',
      },
      {
        title: 'Inception',
        year: '2010',
        runtime: 148,
        tmdbId: 27205,
        mediaType: 'movie',
      },
      {
        title: 'The Dark Knight Rises',
        year: '2012',
        runtime: 164,
        tmdbId: 49026,
        mediaType: 'movie',
      },
      {
        title: 'Interstellar',
        year: '2014',
        runtime: 169,
        tmdbId: 157336,
        mediaType: 'movie',
      },
      {
        title: 'Dunkirk',
        year: '2017',
        runtime: 106,
        tmdbId: 374720,
        mediaType: 'movie',
      },
      {
        title: 'Tenet',
        year: '2020',
        runtime: 150,
        tmdbId: 577922,
        mediaType: 'movie',
      },
      {
        title: 'Oppenheimer',
        year: '2023',
        runtime: 180,
        tmdbId: 872585,
        mediaType: 'movie',
      },
    ],
  },
  {
    id: 'ghibli-journey',
    title: 'Studio Ghibli Journey',
    description: 'The complete Studio Ghibli filmography',
    category: 'studio',
    icon: '◈',
    totalRuntime: 1980,
    itemCount: 23,
    items: [
      {
        title: 'Nausicaä of the Valley of the Wind',
        year: '1984',
        runtime: 117,
        tmdbId: 12429,
        mediaType: 'movie',
      },
      {
        title: 'Castle in the Sky',
        year: '1986',
        runtime: 124,
        tmdbId: 12431,
        mediaType: 'movie',
      },
      {
        title: 'My Neighbor Totoro',
        year: '1988',
        runtime: 86,
        tmdbId: 8392,
        mediaType: 'movie',
      },
      {
        title: 'Grave of the Fireflies',
        year: '1988',
        runtime: 89,
        tmdbId: 12477,
        mediaType: 'movie',
      },
      {
        title: "Kiki's Delivery Service",
        year: '1989',
        runtime: 103,
        tmdbId: 16859,
        mediaType: 'movie',
      },
      {
        title: 'Only Yesterday',
        year: '1991',
        runtime: 118,
        tmdbId: 21060,
        mediaType: 'movie',
      },
      {
        title: 'Porco Rosso',
        year: '1992',
        runtime: 94,
        tmdbId: 11621,
        mediaType: 'movie',
      },
      {
        title: 'Pom Poko',
        year: '1994',
        runtime: 119,
        tmdbId: 12500,
        mediaType: 'movie',
      },
      {
        title: 'Whisper of the Heart',
        year: '1995',
        runtime: 111,
        tmdbId: 37797,
        mediaType: 'movie',
      },
      {
        title: 'Princess Mononoke',
        year: '1997',
        runtime: 134,
        tmdbId: 128,
        mediaType: 'movie',
      },
      {
        title: 'My Neighbors the Yamadas',
        year: '1999',
        runtime: 104,
        tmdbId: 12505,
        mediaType: 'movie',
      },
      {
        title: 'Spirited Away',
        year: '2001',
        runtime: 125,
        tmdbId: 129,
        mediaType: 'movie',
      },
      {
        title: 'The Cat Returns',
        year: '2002',
        runtime: 75,
        tmdbId: 12497,
        mediaType: 'movie',
      },
      {
        title: "Howl's Moving Castle",
        year: '2004',
        runtime: 119,
        tmdbId: 4935,
        mediaType: 'movie',
      },
      {
        title: 'Tales from Earthsea',
        year: '2006',
        runtime: 115,
        tmdbId: 12516,
        mediaType: 'movie',
      },
      {
        title: 'Ponyo',
        year: '2008',
        runtime: 101,
        tmdbId: 12429,
        mediaType: 'movie',
      },
      {
        title: 'The Secret World of Arrietty',
        year: '2010',
        runtime: 94,
        tmdbId: 49013,
        mediaType: 'movie',
      },
      {
        title: 'From Up on Poppy Hill',
        year: '2011',
        runtime: 91,
        tmdbId: 75623,
        mediaType: 'movie',
      },
      {
        title: 'The Wind Rises',
        year: '2013',
        runtime: 126,
        tmdbId: 149870,
        mediaType: 'movie',
      },
      {
        title: 'The Tale of the Princess Kaguya',
        year: '2013',
        runtime: 137,
        tmdbId: 149871,
        mediaType: 'movie',
      },
      {
        title: 'When Marnie Was There',
        year: '2014',
        runtime: 103,
        tmdbId: 242224,
        mediaType: 'movie',
      },
      {
        title: 'The Red Turtle',
        year: '2016',
        runtime: 80,
        tmdbId: 368022,
        mediaType: 'movie',
      },
      {
        title: 'The Boy and the Heron',
        year: '2023',
        runtime: 124,
        tmdbId: 508965,
        mediaType: 'movie',
      },
    ],
  },
  {
    id: 'mcu-timeline',
    title: 'MCU Timeline',
    description: 'The Marvel Cinematic Universe in release order',
    category: 'franchise',
    icon: '◉',
    totalRuntime: 3272,
    itemCount: 33,
    items: [
      {
        title: 'Iron Man',
        year: '2008',
        runtime: 126,
        tmdbId: 1726,
        mediaType: 'movie',
      },
      {
        title: 'The Incredible Hulk',
        year: '2008',
        runtime: 112,
        tmdbId: 1724,
        mediaType: 'movie',
      },
      {
        title: 'Iron Man 2',
        year: '2010',
        runtime: 124,
        tmdbId: 10138,
        mediaType: 'movie',
      },
      {
        title: 'Thor',
        year: '2011',
        runtime: 115,
        tmdbId: 10195,
        mediaType: 'movie',
      },
      {
        title: 'Captain America: The First Avenger',
        year: '2011',
        runtime: 124,
        tmdbId: 1771,
        mediaType: 'movie',
      },
      {
        title: 'The Avengers',
        year: '2012',
        runtime: 143,
        tmdbId: 24428,
        mediaType: 'movie',
      },
      {
        title: 'Iron Man 3',
        year: '2013',
        runtime: 130,
        tmdbId: 68721,
        mediaType: 'movie',
      },
      {
        title: 'Thor: The Dark World',
        year: '2013',
        runtime: 112,
        tmdbId: 76338,
        mediaType: 'movie',
      },
      {
        title: 'Captain America: The Winter Soldier',
        year: '2014',
        runtime: 136,
        tmdbId: 100402,
        mediaType: 'movie',
      },
      {
        title: 'Guardians of the Galaxy',
        year: '2014',
        runtime: 121,
        tmdbId: 118340,
        mediaType: 'movie',
      },
      {
        title: 'Avengers: Age of Ultron',
        year: '2015',
        runtime: 141,
        tmdbId: 99861,
        mediaType: 'movie',
      },
      {
        title: 'Ant-Man',
        year: '2015',
        runtime: 117,
        tmdbId: 102899,
        mediaType: 'movie',
      },
      {
        title: 'Captain America: Civil War',
        year: '2016',
        runtime: 147,
        tmdbId: 271110,
        mediaType: 'movie',
      },
      {
        title: 'Doctor Strange',
        year: '2016',
        runtime: 115,
        tmdbId: 284052,
        mediaType: 'movie',
      },
      {
        title: 'Guardians of the Galaxy Vol. 2',
        year: '2017',
        runtime: 136,
        tmdbId: 283995,
        mediaType: 'movie',
      },
      {
        title: 'Spider-Man: Homecoming',
        year: '2017',
        runtime: 133,
        tmdbId: 315635,
        mediaType: 'movie',
      },
      {
        title: 'Thor: Ragnarok',
        year: '2017',
        runtime: 130,
        tmdbId: 284053,
        mediaType: 'movie',
      },
      {
        title: 'Black Panther',
        year: '2018',
        runtime: 134,
        tmdbId: 284054,
        mediaType: 'movie',
      },
      {
        title: 'Avengers: Infinity War',
        year: '2018',
        runtime: 149,
        tmdbId: 299536,
        mediaType: 'movie',
      },
      {
        title: 'Ant-Man and the Wasp',
        year: '2018',
        runtime: 118,
        tmdbId: 363088,
        mediaType: 'movie',
      },
      {
        title: 'Captain Marvel',
        year: '2019',
        runtime: 123,
        tmdbId: 299537,
        mediaType: 'movie',
      },
      {
        title: 'Avengers: Endgame',
        year: '2019',
        runtime: 181,
        tmdbId: 299534,
        mediaType: 'movie',
      },
      {
        title: 'Spider-Man: Far From Home',
        year: '2019',
        runtime: 129,
        tmdbId: 429617,
        mediaType: 'movie',
      },
      {
        title: 'Black Widow',
        year: '2021',
        runtime: 134,
        tmdbId: 497698,
        mediaType: 'movie',
      },
      {
        title: 'Shang-Chi',
        year: '2021',
        runtime: 132,
        tmdbId: 566525,
        mediaType: 'movie',
      },
      {
        title: 'Eternals',
        year: '2021',
        runtime: 156,
        tmdbId: 524434,
        mediaType: 'movie',
      },
      {
        title: 'Spider-Man: No Way Home',
        year: '2021',
        runtime: 148,
        tmdbId: 634649,
        mediaType: 'movie',
      },
      {
        title: 'Doctor Strange in the Multiverse of Madness',
        year: '2022',
        runtime: 126,
        tmdbId: 453395,
        mediaType: 'movie',
      },
      {
        title: 'Thor: Love and Thunder',
        year: '2022',
        runtime: 119,
        tmdbId: 616037,
        mediaType: 'movie',
      },
      {
        title: 'Black Panther: Wakanda Forever',
        year: '2022',
        runtime: 161,
        tmdbId: 505642,
        mediaType: 'movie',
      },
      {
        title: 'Ant-Man and the Wasp: Quantumania',
        year: '2023',
        runtime: 125,
        tmdbId: 640146,
        mediaType: 'movie',
      },
      {
        title: 'Guardians of the Galaxy Vol. 3',
        year: '2023',
        runtime: 150,
        tmdbId: 447365,
        mediaType: 'movie',
      },
      {
        title: 'The Marvels',
        year: '2023',
        runtime: 105,
        tmdbId: 609681,
        mediaType: 'movie',
      },
    ],
  },
  {
    id: 'best-picture',
    title: 'Best Picture Winners',
    description: 'Recent Academy Award winners for Best Picture',
    category: 'genre',
    icon: '◇',
    totalRuntime: 1420,
    itemCount: 10,
    items: [
      {
        title: 'Parasite',
        year: '2019',
        runtime: 132,
        tmdbId: 496243,
        mediaType: 'movie',
      },
      {
        title: 'Nomadland',
        year: '2020',
        runtime: 108,
        tmdbId: 581734,
        mediaType: 'movie',
      },
      {
        title: 'CODA',
        year: '2021',
        runtime: 111,
        tmdbId: 776503,
        mediaType: 'movie',
      },
      {
        title: 'Everything Everywhere All at Once',
        year: '2022',
        runtime: 139,
        tmdbId: 545611,
        mediaType: 'movie',
      },
      {
        title: 'Oppenheimer',
        year: '2023',
        runtime: 180,
        tmdbId: 872585,
        mediaType: 'movie',
      },
    ],
  },
  {
    id: 'bond-marathon',
    title: 'James Bond Marathon',
    description: 'All 25 official Bond films in order',
    category: 'franchise',
    icon: '◆',
    totalRuntime: 2882,
    itemCount: 25,
    items: [
      {
        title: 'Dr. No',
        year: '1962',
        runtime: 110,
        tmdbId: 646,
        mediaType: 'movie',
      },
      {
        title: 'From Russia with Love',
        year: '1963',
        runtime: 115,
        tmdbId: 657,
        mediaType: 'movie',
      },
      {
        title: 'Goldfinger',
        year: '1964',
        runtime: 110,
        tmdbId: 660,
        mediaType: 'movie',
      },
      {
        title: 'Thunderball',
        year: '1965',
        runtime: 130,
        tmdbId: 661,
        mediaType: 'movie',
      },
      {
        title: 'You Only Live Twice',
        year: '1967',
        runtime: 117,
        tmdbId: 667,
        mediaType: 'movie',
      },
      {
        title: "On Her Majesty's Secret Service",
        year: '1969',
        runtime: 142,
        tmdbId: 668,
        mediaType: 'movie',
      },
      {
        title: 'Diamonds Are Forever',
        year: '1971',
        runtime: 120,
        tmdbId: 671,
        mediaType: 'movie',
      },
      {
        title: 'Live and Let Die',
        year: '1973',
        runtime: 121,
        tmdbId: 673,
        mediaType: 'movie',
      },
      {
        title: 'The Man with the Golden Gun',
        year: '1974',
        runtime: 125,
        tmdbId: 675,
        mediaType: 'movie',
      },
      {
        title: 'The Spy Who Loved Me',
        year: '1977',
        runtime: 125,
        tmdbId: 679,
        mediaType: 'movie',
      },
      {
        title: 'Moonraker',
        year: '1979',
        runtime: 126,
        tmdbId: 681,
        mediaType: 'movie',
      },
      {
        title: 'For Your Eyes Only',
        year: '1981',
        runtime: 127,
        tmdbId: 682,
        mediaType: 'movie',
      },
      {
        title: 'Octopussy',
        year: '1983',
        runtime: 131,
        tmdbId: 683,
        mediaType: 'movie',
      },
      {
        title: 'A View to a Kill',
        year: '1985',
        runtime: 131,
        tmdbId: 685,
        mediaType: 'movie',
      },
      {
        title: 'The Living Daylights',
        year: '1987',
        runtime: 130,
        tmdbId: 687,
        mediaType: 'movie',
      },
      {
        title: 'Licence to Kill',
        year: '1989',
        runtime: 133,
        tmdbId: 688,
        mediaType: 'movie',
      },
      {
        title: 'GoldenEye',
        year: '1995',
        runtime: 130,
        tmdbId: 710,
        mediaType: 'movie',
      },
      {
        title: 'Tomorrow Never Dies',
        year: '1997',
        runtime: 119,
        tmdbId: 707,
        mediaType: 'movie',
      },
      {
        title: 'The World Is Not Enough',
        year: '1999',
        runtime: 128,
        tmdbId: 706,
        mediaType: 'movie',
      },
      {
        title: 'Die Another Day',
        year: '2002',
        runtime: 133,
        tmdbId: 708,
        mediaType: 'movie',
      },
      {
        title: 'Casino Royale',
        year: '2006',
        runtime: 144,
        tmdbId: 36557,
        mediaType: 'movie',
      },
      {
        title: 'Quantum of Solace',
        year: '2008',
        runtime: 106,
        tmdbId: 10764,
        mediaType: 'movie',
      },
      {
        title: 'Skyfall',
        year: '2012',
        runtime: 143,
        tmdbId: 37724,
        mediaType: 'movie',
      },
      {
        title: 'Spectre',
        year: '2015',
        runtime: 148,
        tmdbId: 206647,
        mediaType: 'movie',
      },
      {
        title: 'No Time to Die',
        year: '2021',
        runtime: 163,
        tmdbId: 370172,
        mediaType: 'movie',
      },
    ],
  },
]

export function getChallengeById(id: string): FilmChallenge | undefined {
  return challenges.find((c) => c.id === id)
}

export function getChallengesByCategory(
  category: FilmChallenge['category']
): FilmChallenge[] {
  return challenges.filter((c) => c.category === category)
}
