import jsPDF from 'jspdf'
import { WatchPlan } from '@/types/media'

function formatHours(hours: number): string {
  const h = Math.floor(hours)
  const m = Math.round((hours - h) * 60)
  if (m === 0) return `${h}h`
  return `${h}h ${m}m`
}

export async function exportPlanAsPdf(
  plan: WatchPlan,
  title: string,
  releaseYear: string
) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2

  // Background
  doc.setFillColor(26, 20, 16)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')

  // Gold accent line
  doc.setDrawColor(201, 146, 42)
  doc.setLineWidth(0.5)
  doc.line(margin, 28, pageWidth - margin, 28)

  // Header
  doc.setTextColor(201, 146, 42)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text('BINGELY · WATCH PLAN', margin, 22)

  // Title
  doc.setTextColor(242, 232, 213)
  doc.setFontSize(32)
  doc.setFont('helvetica', 'bold')
  doc.text(title, margin, 48)

  // Year
  doc.setTextColor(242, 232, 213)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(releaseYear, margin, 56)

  // Divider
  doc.setDrawColor(201, 146, 42)
  doc.setLineWidth(0.2)
  doc.line(margin, 62, pageWidth - margin, 62)

  // Stats row
  const stats =
    plan.mediaType === 'tv'
      ? [
          { label: 'COMPLETION', value: plan.completionDate },
          { label: 'TOTAL WEEKS', value: `${plan.totalWeeks} weeks` },
          { label: 'EPS / WEEK', value: `${plan.episodesPerWeek} eps` },
          { label: 'TOTAL HOURS', value: formatHours(plan.totalHours) },
        ]
      : [
          { label: 'RUNTIME', value: formatHours(plan.totalHours) },
          { label: 'WATCH DATE', value: plan.completionDate },
        ]

  const colWidth = contentWidth / stats.length
  stats.forEach((s, i) => {
    const x = margin + i * colWidth
    doc.setTextColor(201, 146, 42)
    doc.setFontSize(7)
    doc.text(s.label, x, 72)
    doc.setTextColor(242, 232, 213)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(s.value, x, 80)
    doc.setFont('helvetica', 'normal')
  })

  // Divider
  doc.setDrawColor(242, 232, 213)
  doc.setLineWidth(0.1)
  doc.line(margin, 88, pageWidth - margin, 88)

  if (plan.mediaType === 'tv') {
    // Milestones
    doc.setTextColor(201, 146, 42)
    doc.setFontSize(8)
    doc.text('MILESTONES', margin, 98)

    plan.milestones.forEach((m, i) => {
      const y = 106 + i * 10
      doc.setTextColor(242, 232, 213)
      doc.setFontSize(10)
      doc.text(`${m.label}`, margin, y)
      doc.setTextColor(242, 232, 213)
      doc.setFontSize(8)
      doc.text(
        `Week ${m.week} · Ep ${m.episode} · ${m.percent}%`,
        margin + 60,
        y
      )
    })

    // Weekly breakdown header
    const weekStartY = 106 + plan.milestones.length * 10 + 10
    doc.setTextColor(201, 146, 42)
    doc.setFontSize(8)
    doc.text('WEEK BY WEEK', margin, weekStartY)

    // Weekly rows — up to 20 weeks per page
    const maxWeeks = Math.min(plan.weeklyBlocks.length, 20)
    plan.weeklyBlocks.slice(0, maxWeeks).forEach((block, i) => {
      const y = weekStartY + 8 + i * 8
      if (y > pageHeight - margin) return

      doc.setTextColor(242, 232, 213)
      doc.setFontSize(8)
      doc.text(`Week ${block.week}`, margin, y)
      doc.text(`Eps ${block.startEpisode}–${block.endEpisode}`, margin + 24, y)
      doc.text(`${block.episodes} eps`, margin + 80, y)
      doc.text(`${block.cumulativePercent}%`, margin + 110, y)

      // Progress bar
      const barX = margin + 125
      const barW = contentWidth - 125
      doc.setFillColor(44, 24, 16)
      doc.rect(barX, y - 3, barW, 3, 'F')
      doc.setFillColor(201, 146, 42)
      doc.rect(barX, y - 3, (barW * block.cumulativePercent) / 100, 3, 'F')
    })

    if (plan.weeklyBlocks.length > 20) {
      const y = weekStartY + 8 + 20 * 8
      doc.setTextColor(242, 232, 213)
      doc.setFontSize(8)
      doc.text(`... and ${plan.weeklyBlocks.length - 20} more weeks`, margin, y)
    }
  }

  // Footer
  doc.setDrawColor(201, 146, 42)
  doc.setLineWidth(0.2)
  doc.line(margin, pageHeight - 16, pageWidth - margin, pageHeight - 16)
  doc.setTextColor(201, 146, 42)
  doc.setFontSize(7)
  doc.text('Generated by Bingely · bingely.app', margin, pageHeight - 10)

  doc.save(`${title.replace(/\s+/g, '-').toLowerCase()}-watch-plan.pdf`)
}
