import { MediaItem } from '@/types/media'

export const mockResults: MediaItem[] = [
  {
    id: 1,
    title: 'One Piece',
    posterPath: null,
    releaseYear: '1999',
    mediaType: 'tv',
    voteAverage: 8.9,
    episodeCount: 1122,
    seasonCount: 21,
  },
  {
    id: 2,
    title: 'Breaking Bad',
    posterPath: null,
    releaseYear: '2008',
    mediaType: 'tv',
    voteAverage: 9.5,
    episodeCount: 62,
    seasonCount: 5,
  },
  {
    id: 3,
    title: 'The Godfather',
    posterPath: null,
    releaseYear: '1972',
    mediaType: 'movie',
    voteAverage: 9.2,
    runtime: 175,
  },
  {
    id: 4,
    title: 'Neon Genesis Evangelion',
    posterPath: null,
    releaseYear: '1995',
    mediaType: 'tv',
    voteAverage: 8.5,
    episodeCount: 26,
    seasonCount: 1,
  },
  {
    id: 5,
    title: 'Spirited Away',
    posterPath: null,
    releaseYear: '2001',
    mediaType: 'movie',
    voteAverage: 8.6,
    runtime: 125,
  },
  {
    id: 6,
    title: 'The Wire',
    posterPath: null,
    releaseYear: '2002',
    mediaType: 'tv',
    voteAverage: 9.3,
    episodeCount: 60,
    seasonCount: 5,
  },
]
